### ISSUE TITLE
Remove alloc dependency

### ISSUE THREAD

**Issue by willemml** [nw-rs/citrus-cas#1]
This crate would ideally not require a memory allocator.

**Comment by willemml** [comment]
Something like [`heapless`](https://crates.io/crates/heapless) or [`arrayvec`](https://crates.io/crates/arrayvec) should be used if necessary but should be avoided. If used array sizes should all be easily changeable as constants or generics (unless they should not be changeable by users of the library).

**Comment by MixedMatched** [comment]
commit acf2dc2b51d162e26fbb6211a049b4c5a44c4b41 resolved this.
