### ISSUE TITLE
name change tracker

### ISSUE THREAD

**Issue by MixedMatched** [nw-rs/citrus-cas#44]
this is a tracking issue for the potential name changes for this project

- fruit themed:
  - lemonlime
  - limecas
  - lemoncas (this is the one I'm leaning towards)
  - citrus-cas

**Comment by JarnaChao09** [comment]
just a small note, but google search results for lemoncas conflict with lemoncash...as well as lemoncams (do not look that one up)

**Comment by willemml** [comment]
Too bad about search results for lemoncams, if what I am guessing you are saying about it is correct, then it will suck for getting higher on the Google search rankings.

LemonCAS is my favourite so far besides that small issue.

**Comment by willemml** [comment]
citrus-cas was chosen in a Discord conversation.
